name: stack_trace_info
description: Provides a simple yet powerful way to parse and extract detailed information from Dart stack traces.
version: 1.0.1
repository: https://github.com/astudilloalex/stack-trace-info-dart-package

environment:
  sdk: '>=3.1.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lint: ^2.3.0
  test: ^1.24.0
